runtime: python27
api_version: 1
threadsafe: true

handlers:

# Simple static files:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /icons
  static_dir: static/icons

- url: /favicon\.ico
  static_files: static/icons/favicon.ico
  upload: static/icons/favicon\.ico

# Homepage and help page:
- url: /
  script: main.app
  secure: always

- url: /help
  script: main.app
  secure: always

# Everything else must be secure and authenticated
- url: /.*
  script: main.app
  secure: always
  login: required


# http://code.google.com/appengine/docs/python/config/appconfig.html#Builtin_Handlers
builtins:
#- datastore_admin: on
- appstats: on
- admin_redirect: on

libraries:
- name: jinja2
  version: 2.6
